1. Write a Python Program to Add Two Matrices?

In [1]:
l=[1,2,3,4]
g=[5,6,7,8]
f=[]
for i in range(len(l)):
    f.append(l[i]+g[i])
print(f)

[6, 8, 10, 12]


2 . Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
l=[[1,4],[5,6]]
g=[[5,6],[7,8]]
print(np.dot(l,g))

[[33 38]
 [67 78]]


3 . Write a Python Program to Transpose a Matrix?

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Original Array:\n{arr}')

arr_T = arr.transpose()

print(f'Transposed Array:\n{arr_T}')

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


4 . Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
l=['ravi','teja','ineuron']
l.sort()
print(l)

['ineuron', 'ravi', 'teja']


5 . Write a Python Program to Remove Punctuation From a String?

In [5]:
punct = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
l='hii,, iam Ravit_ej-a'
t=""
for i in l:
    if(i not in punct):
        t=t+i
print(t)

hii iam Raviteja
